services:
  front:
    image: front
    build:
      context: ./requirements/front
    container_name: front
    ports:
      - "80:80"
      - "443:443"
    networks:
      - front-tier
    env_file: .env
    depends_on:
      - back
  back:
    image: back
    build:
      context: ./requirements/back
      dockerfile: Dockerfile
    container_name: back
    networks:
      - front-tier
      - back-tier
    env_file: .env
    depends_on:
      - db
  ai:
    image: ai
    build:
      context: ./requirements/ai
      dockerfile: Dockerfile
    container_name: ai
    networks:
      - back-tier
    env_file: .env
  db:
    image: postgres:15-alpine3.18
    container_name: db
    restart: always
    networks:
      - back-tier
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
    volumes:
      - db-data:/var/lib/postgresql/data
    expose:
      - $DB_PORT
  
volumes:
  db-data:

networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge
